<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Series extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Series_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'series/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'series/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'series/index.html';
            $config['first_url'] = base_url() . 'series/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Series_model->total_rows($q);
        $series = $this->Series_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'series_data' => $series,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => 'Data Series',
            'konten' => 'series/series_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Series_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_series' => $row->id_series,
		'series' => $row->series,
	    );
            $this->load->view('series/series_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('series'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => 'series/series_form',
            'konten' => 'series/series_form',
            'button' => 'Create',
            'action' => site_url('series/create_action'),
	    'id_series' => set_value('id_series'),
	    'series' => set_value('series'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'series' => $this->input->post('series',TRUE),
	    );

            $this->Series_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('series'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Series_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => 'series/series_form',
                'konten' => 'series/series_form',
                'button' => 'Update',
                'action' => site_url('series/update_action'),
		'id_series' => set_value('id_series', $row->id_series),
		'series' => set_value('series', $row->series),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('series'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_series', TRUE));
        } else {
            $data = array(
		'series' => $this->input->post('series',TRUE),
	    );

            $this->Series_model->update($this->input->post('id_series', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('series'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Series_model->get_by_id($id);

        if ($row) {
            $this->Series_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('series'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('series'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('series', 'series', 'trim|required');

	$this->form_validation->set_rules('id_series', 'id_series', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Series.php */
/* Location: ./application/controllers/Series.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2020-10-06 09:23:18 */
/* https://jualkoding.com */