<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penjualan_model extends CI_Model
{

    public $table = 'penjualan';
    public $id = 'id_penjualan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function Stok_lama($id_mobil){
        $sql=$this->db->query("SELECT stok_awal,stok_keluar FROM `mobil` WHERE `id_mobil` = $id_mobil ");
        return $sql->row();
    }
    function Kurang_stok($id_mobil){
        $data_transaksi=1;
        $sql=$this->db->query("
        UPDATE `mobil` SET `stok_keluar` = '$data_transaksi' WHERE `mobil`.`id_mobil` = $id_mobil;
        ");
    return $sql ;	
    }

    function tampil_data_penjualan_lap(){
       $tgl1=$this->input->post('tgl1');
       $tgl2=$this->input->post('tgl2');
      $sql=$this->db->query("select * FROM penjualan WHERE tanggal BETWEEN '$tgl1' AND '$tgl2'");
        return $sql;
    }
    function cetak_data_penjualan_lap(){
        $tgl1=$this->input->post('tgl1');
        $tgl2=$this->input->post('tgl2');
        $sql=$this->db->query("select * FROM penjualan WHERE tanggal BETWEEN '$tgl1' AND '$tgl2'");
        return $sql;
    }

    function Tampil_data_konsumen($id_konsumen){
        $sql=$this->db->query("SELECT nama_konsumen FROM `konsumen` WHERE `id_konsumen` = $id_konsumen ");
        return $sql->row();
    }

    function Tampil_data_mobil($id_mobil){
        $sql=$this->db->query("SELECT judul,harga FROM `mobil` WHERE `id_mobil` = $id_mobil ");
        return $sql->row();
    }

    function Tampil_data_user($id_user){
        $sql=$this->db->query("SELECT nama_lengkap FROM `a_user` WHERE `id_user` = $id_user ");
        return $sql->row();
    }

    function tampil_data_penjualan_lap_graf($tgl1,$tgl2){
    
      $sql=$this->db->query("SELECT *, count(1) as jumlah FROM penjualan WHERE tanggal BETWEEN '$tgl1' AND '$tgl2' group by tanggal");
      return $sql;
     }

    //  function Cetak_data_penjualan_lap($tgl1,$tgl2){
    //     $sql=$this->db->query("select * FROM penjualan WHERE tanggal BETWEEN '$tgl1' AND '$tgl2'");
    //       return $sql;
    //      }
    ///hendra


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penjualan', $q);
	$this->db->or_like('kode_transaksi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('tipe_pembayaran', $q);
	$this->db->or_like('id_mobil', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('user_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penjualan', $q);
	$this->db->or_like('kode_transaksi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('tipe_pembayaran', $q);
	$this->db->or_like('id_mobil', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('user_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penjualan_model.php */
/* Location: ./application/models/Penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-26 17:55:06 */
/* http://harviacode.com */